---
kind: Namespace
apiVersion: v1
metadata:
  name: telco-cloud-patch-operator
  labels:
    openshift.io/cluster-monitoring: "true"
---
apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  name: patch-operator
---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: patch-operator-subscription
spec:
  channel: "stable" 
  installPlanApproval: "Manual"
  name: patch-operator
  source: community-operators
  sourceNamespace: openshift-marketplace