apiVersion: redhatcop.redhat.io/v1alpha1
kind: Patch
metadata:
  name: node-patch
  namespace: patch-operator
spec:
  patches:
    simple-patch:
      patchTemplate: |
        metadata:
          labels:
            node-role.kubernetes.io/worker-sriov: ""
      patchType: application/strategic-merge-patch+json
      targetObjectRef:
        apiVersion: v1
        kind: Node
        labelSelector:
          matchExpressions:
          - key: kubernetes.io/hostname
            operator: In
            values:
            - worker01
  serviceAccountRef:
    name: node-label-patcher
