apiVersion: redhatcop.redhat.io/v1alpha1
kind: Patch
metadata:
  name: node-patch-test
  namespace: patch-operator
spec:
  patches:
    simple-patch:
      patchTemplate: |
        metadata:
          labels:
            mabe.cloud/storage-iscsi: true 
      patchType: application/strategic-merge-patch+json
      targetObjectRef:
        apiVersion: v1
        kind: Node
        labelSelector:
          matchExpressions:
          - key: kubernetes.io/hostname
            operator: In
            values:
            - worker02
  serviceAccountRef:
    name: node-label-patcher
