---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonAnnotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
    
bases:
  - ../../base

patchesStrategicMerge:
  - ./patches/logging-target.yml

patchesJson6902: