---
apiVersion: redhatcop.redhat.io/v1alpha1
kind: Patch
metadata:
  name: worker01
spec:
  patches:
    simple-patch:
      patchTemplate: |
        metadata:
          labels:
            mabe.cloud/network-class: "ovn"
            mabe.cloud/storage-class-iscsi: "true"
            mabe.cloud/storage-class-block: "true"
      patchType: application/strategic-merge-patch+json
      targetObjectRef:
        apiVersion: v1
        kind: Node
        labelSelector:
          matchLabels:
            kubernetes.io/hostname: worker01
  serviceAccountRef:
    name: node-label-patcher